### ISSUE TITLE
Officially support Python 3.9, 3.10 on PyPI

### ISSUE THREAD

**Issue by uri-rodberg** [boto/s3transfer#227]
PyPi only lists support of `s3transfer` to Python <= 3.8. I would like to see `s3transfer` officially supporting newer versions - Python 3.9, 3.10. And also, development status on PyPI is `3 - Alpha` - can you increase it to `5 - Production/Stable` maybe?

From my testing, `s3transfer==0.5.0` works with Python 3.9, 3.10.

**Comment by nateprewitt** [comment]
Hi @uri-rodberg, we have added updated [version support](https://github.com/boto/s3transfer/blob/develop/setup.py#L48-L49) to the setup.py for s3transfer. There just hasn't been a feature update to warrant a new upload to PyPI since then. The next release will update the public metadata.

In regards to Alpha vs Stable, s3transfer is still considered an implementation detail of Botocore. It's not intended or supported as a stand-alone product which is the reason for the current classification. If the library ever reaches a 1.0 release, it should have the development status updated.

**Comment by uri-rodberg** [comment]
Thank you.

**Comment by jpl-jengelke** [comment]
@uri-rodberg @nateprewitt The `s3transfer` package may run on newer Pythons, but threading changed in Python 3.8, so if it is being used in a threaded application, something is broken at `0.4.0`. (It bit me!) [This ticket](https://github.com/boto/s3transfer/issues/197) advises rolling the product back to `0.3.x` (rolling back Boto3 to an older version effectively does just that) when those issues pop up.
