### ISSUE TITLE
Timeline for GA?

### ISSUE THREAD

**Issue by zachrattner** [boto/s3transfer#93]
Is this code recommended for use in production systems? Is there a timeline for integrating this with the main boto libs?

**Comment by kyleknap** [comment]
So technically this library is being used in production systems as both the AWS CLI and boto3 leverage it for their managed s3 transfer functionality. Those libraries are stable and their functionality is recommended for production systems.

At the moment there is no timeline for GA'ing the library. Using this library yourself directly in production systems is generally not recommended because the interface may have breaking changes as it evolves. And as stated in the README, if you do plan to use it in production it is recommended to lock to a minor version at least.
